//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class country_lang_link
    {
        public int id { get; set; }
        [Required()]
        public int country_id { get; set; }
        [Required()]
        public int lang_id { get; set; }
    
        public virtual country country { get; set; }
        public virtual language language { get; set; }
    }
}
