//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public country()
        {
            this.country_lang_link = new HashSet<country_lang_link>();
        }
    
        public int id { get; set; }
        [StringLength(40)]
        [Required()]
        public string name { get; set; }
        [Required()]
        public int population { get; set; }
        [StringLength(40)]
        [Required()]
        public string capital { get; set; }
        [StringLength(40)]
        [Required()]
        public string continent { get; set; }
        [Required()]
        public int area { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<country_lang_link> country_lang_link { get; set; }
    }
}
