//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// Language family - language link.
    /// </summary>
    public partial class langfam_lang_link
    {
        /// <summary>
        /// Id of a langfam_lang_link.
        /// </summary>
        public int id { get; set; }
        /// <summary>
        /// Language family id of a langfam_lang_link.
        /// </summary>
        [Required()]
        public int langfam_id { get; set; }
        /// <summary>
        /// Language id of a langfam_lang_link.
        /// </summary>
        [Required()]
        public int lang_id { get; set; }
        /// <summary>
        /// Language table.
        /// </summary>
        public virtual language language { get; set; }
        /// <summary>
        /// Language family table.
        /// </summary>
        public virtual language_family language_family { get; set; }
    }
}
